import { EggObject } from "../types/Types";
export const eggVarieties: EggObject[] = [
  {
    name: "Dango Rango",
    rate: 0.05,
    image: "dango-rango-egg.webp",
    rarity: "",
  },
  {
    name: "'Star Guardian' Furyhorn",
    rate: 0.04,
    image: "starguardian-furyhorn-egg.webp",
    rarity: "",
  },
  {
    name: "'Star Guardian' Hushtail",
    rate: 0.04,
    image: "starguardian-hushtail-egg.webp",
    rarity: "",
  },
  {
    name: "Neon Nights QiQi",
    rate: 0.04,
    image: "neon-nights-qiqi-egg.webp",
    rarity: "",
  },
  {
    name: "Series 3 Rare Egg",
    rate: 0.04,
    image: "series-3-egg.webp",
    rarity: "",
  },
  {
    name: "Poggles and Burno Egg",
    rate: 0.04,
    image: "burno-poggles-egg.webp",
    rarity: "",
  },
  {
    name: "Bun Bun",
    rate: 0.04,
    image: "bunbun-egg.webp",
    rarity: "",
  },
  {
    name: "Bungo",
    rate: 0.04,
    image: "bungo-egg.webp",
    rarity: "",
  },
  {
    name: "Noctero",
    rate: 0.04,
    image: "noctero-egg.webp",
    rarity: "",
  },
  {
    name: "Prancie",
    rate: 0.04,
    image: "prancie-egg.webp",
    rarity: "",
  },
  {
    name: "Scuttle",
    rate: 0.04,
    image: "scuttle-egg.webp",
    rarity: "",
  },
  {
    name: "Shork",
    rate: 0.04,
    image: "shork-egg.webp",
    rarity: "",
  },
  {
    name: "Whisker",
    rate: 0.04,
    image: "whisker-egg.webp",
    rarity: "",
  },
  {
    name: "Neon Nights Fenroar",
    rate: 0.03,
    image: "neon-nights-fenroar-egg.webp",
    rarity: "",
  },
  {
    name: "Neon Nights Lightcharger",
    rate: 0.03,
    image: "neon-nights-lightcharger-egg.webp",
    rarity: "",
  },
  {
    name: "Cosmic Companions Egg",
    rate: 0.03,
    image: "cosmic-companions-egg.webp",
    rarity: "",
  },
  {
    name: "Fearless Fellowship Egg",
    rate: 0.03,
    image: "fearless-fellowship-egg.webp",
    rarity: "",
  },
  {
    name: "Friends from Afar Egg",
    rate: 0.03,
    image: "friends-from-afar-egg.webp",
    rarity: "",
  },
  {
    name: "Heroic Hatchlings",
    rate: 0.03,
    image: "heroic-hatchlings-egg.webp",
    rarity: "",
  },
  {
    name: "Immortal Creatures Egg",
    rate: 0.03,
    image: "immortal-creatures-egg.webp",
    rarity: "",
  },
  {
    name: "Ingenious Inventors Egg",
    rate: 0.03,
    image: "ingenious-inventors-egg.webp",
    rarity: "",
  },
  {
    name: "Inktales Egg",
    rate: 0.03,
    image: "inktales-egg.webp",
    rarity: "",
  },
  {
    name: "K/DA ALL OUT Egg",
    rate: 0.03,
    image: "kda-egg.webp",
    rarity: "",
  },
  {
    name: "Series 4 Star Guardian Egg",
    rate: 0.03,
    image: "star-guardian-egg.webp",
    rarity: "",
  },
  {
    name: "Series 5 True Damage Egg",
    rate: 0.03,
    image: "true-damage-egg.webp",
    rarity: "",
  },
  {
    name: "Magical Misfits Egg",
    rate: 0.03,
    image: "magical-misfits-egg.webp",
    rarity: "",
  },
  {
    name: "Pool Party Choncc",
    rate: 0.03,
    image: "pool-party-choncc-egg.webp",
    rarity: "",
  },
  {
    name: "Spirit Blossom Egg",
    rate: 0.03,
    image: "spirit-blossom-egg.webp",
    rarity: "",
  },
  {
    name: "Chibi PROJECT: Zed",
    rate: 0.02,
    image: "project-zed.webp",
    rarity: "ultimate-icon.png",
  },
];
export const defaultEgg = { image: "zed-cache.png", rarity: "", name: "" };
